#!/bin/sh
#
# Start/stop the aesdsocket server as a daemon.
# Runs after S98aesdchar so the aesdchar driver is loaded first.
#

DAEMON=/usr/bin/aesdsocket
NAME=aesdsocket

case "$1" in
	start)
		echo "Starting $NAME"
		start-stop-daemon -S -n "$NAME" -a "$DAEMON" -- -d
		;;
	stop)
		echo "Stopping $NAME"
		start-stop-daemon -K -n "$NAME" -s TERM
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
